project:
  type: website
  preview:
    port: 4200

website:
  page-navigation: true
  title: "BEE 4750 - Fall 2025"
  description: "Homepage for BEE 4750/5750, Environmental Systems Analysis, at Cornell University, Fall 2025."
  site-url: "https://bee4750.github.io"

  repo-url: https://github.com/bee4750/bee4750.github.io
  repo-actions: [edit, issue]

  open-graph: true


  page-footer:
    right: |
      Made with [Julia](https://julialang.org) and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub]({{< var course.github >}})

    left: |
      Content {{< fa copyright >}} {{< var course.copyright_year >}}  by [{{< var instructor.name_no_title >}}]({{< var instructor.url >}}).
      See the [About page](/about.html) for credit information.<br>
      All content licensed under a {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}
      [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International license (CC BY-NC-SA 4.0)](https://creativecommons.org/licenses/by-nc-sa/4.0/)

  sidebar:
    style: docked
    align: center
    logo: _assets/logos/cornell-reduced-red.svg
    title: "{{< var course.number >}}"
    search: true
    tools: 
      - icon: github
        href: https://github.com/BEE4750/bee4750.github.io
        text: "Github Repository"
      - icon: journal-check
        href: https://canvas.cornell.edu
        text: "Canvas"
      - icon: chat-fill
        text: "Ed Discussion"
        url: https://edstem.org
      - icon: bar-chart-fill
        text: "Gradescope"
        url: https://gradescope.com
    collapse-level: 1
    contents:
      - section: "Course Information"
        contents:
          - href: index.qmd
            text: Overview
          - href: schedule.qmd
            text: Schedule
          - text: Setup
            href: setup.qmd
          - text: FAQ
            href: faq.qmd
          - href: syllabus.qmd
            text: Syllabus
      - section: "Policies"
        contents:
          - href: policies/homework.qmd
            text: "Homework Policies"
          - href: policies/exam.qmd
            text: "Exam Policies"
          - href: policies/grading.qmd
            text: "Grading Policies"
          - href: policies/groups.qmd
            text: "Group Expectations"
          - href: policies/integrity.qmd
            text: "Academic Integrity"
          - href: rubrics/standard.qmd
            text: "Standard Rubric"
      - section: hw.qmd
      - section: labs.qmd
      - section: project.qmd
      - section: "Tutorials"
        contents:
          - href: tutorials/julia-basics.qmd
            text: Julia Basics
          - href: tutorials/julia-plots.qmd
            text: Making Plots
          - href: tutorials/latex-notebook.qmd
            text: Math in Notebooks
          - href: tutorials/julia-jump.qmd
            text: Solving Linear Programs
      - resources.qmd

format:
  html:
    theme: 
      [simplex, sass/theme.scss]
    mainfont: "Atkinson Hyperlegible"
    copy-code: true
    code-overflow: wrap
    toc: true
    anchor-sections: true
    callout-appearance: simple
    reference-location: margin
    citation-location: margin
    code-annotations: select
    html-math-method: mathjax
    include-in-header: mathjax-config.html

bibliography: references.bib
csl: _assets/references/american-geophysical-union.csl

engine: julia
execute: 
  freeze: auto  