---
title: "BEE 4750: Environmental Systems Analysis"
tbl-colwidths: [5, 10, 25, 5, 5, 5, 5]
---

This page contains a schedule of the topics, content, and assignments for the semester.
Note that this schedule will be updated as necessary the semester progresses, with all changes documented here.

::: column-screen-inset-right
| Week | Date        | Topic | Slides | Lab | HW | 
:-----:|:------------|:------|:------:|:--:|:---:|:--:|
| | | ***Module 1: Introduction to Systems Analysis*** | | | | |
| 1    | Mon, Aug 25 | Welcome to BEE 4750! |  | HW1 |  
|      | Wed, Aug 27 | Lab: Setting up Julia and GitHub |  | | |
| 2    | Mon, Sep 01 | **No Class: Labor Day** |  | | | |
|      | Wed, Sep 03 | Modeling Systems | | | | 
| 3    | Mon, Sep 08 |  | | |  | 
|      | Wed, Sep 10 | Dynamics + LCA | | | | 
|  4   | Mon, Sep 15 | | | | HW2 | 
|      | Wed, Sep 17 | Lab | | | | 
|  5    | Mon, Sep 22 | Simulation | | | | 
|   | Wed, Sep 24 | | | | | 
|  6  | Mon, Sep 29 | Monte Carlo | | | HW3 | 
|    | Wed, Oct 01 |  | | | | 
|  7   | Mon, Oct 06 | Lab  | | | | 
|      | Wed, Oct 08 | Tradeoffs and Pareto-Optimality | | | | 
|  8  | Mon, Oct 13 | **No Class: Fall Break** |  | |  |
|   | Wed, Oct 15 | *Midterm 1*  | | | | 
|  9 | Mon, Oct 20 | Optimization | | | | 
|    | Wed, Oct 22 | LP | | | | 
|  10  | Mon, Oct 27 |  | | | HW4 | 
|     | Wed, Oct 29 | Lab  | | | | 
|  11  | Mon, Nov 03 | Power Systems | | | | 
|    | Wed, Nov 05 |  | | | | 
| 12    | Mon, Nov 10 | Gaussian Plumes  | | | HW5 | 
|    | Wed, Nov 12 |  | | | | 
| 13   | Mon, Nov 17 | MILP | | | | 
|    | Wed, Nov 19 | *Prelim 2* | |  | | |
|  14  | Mon, Nov 24 | Lab |  |  |    | HW6  |
|     | Wed, Nov 26 | **No Class: Thanksgiving Break** | | | | 
| 15 | Mon, Dec 01 |  | | | | 
|    | Wed, Dec 03 |  | |  | | 
|  16 | Mon, Dec 08 | | | | |  
:::
