name: Update Notes
on:
  repository_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      GKSwstype: 100
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        submodules: true
        fetch-depth: 0
    - name: Update notes
      run: |
        cd website/lecture-notes
        git branch -u origin/Fall22 Fall22
        cd ..
        git submodule update --remote --recursive
    - name: Copy Notes
      run: |
        cd website
        rsync -R lecture-notes/lecture*/*.html __site/
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: website/__site
