on:
  workflow_dispatch:
  push:
    branches: Fall24

name: Publish site

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Install Julia 1.10
        uses: julia-actions/setup-julia@v2
        with:
          version: '1.10'
      - run: julia -e 'using Pkg; Pkg.activate("."); Pkg.instantiate()'
      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}